#!/usr/bin/env python3
"""tests/game's route: the key masks of a route file (as test/host/playhost.c parses it), its seed / level / money /
enemies, its header's nodark / globals / room lines (playhost's --nodark / --global / --room), and the records
whose frames are held for snapshots.
    mkroute.py <out.h> <route.txt> <seed> <level> <money> <enemies> <tail> "<rec,rec,...>" """
import sys

KEYS = dict(R=1, L=2, U=4, D=8, J=16, A=32, I=64, N=128, B=256, O=512, F=1024, P=2048, S=4096)
out, path, seed, level, money, enemies, tail, snaps = sys.argv[1:9]
m = []
for line in open(path):
    w = line.split('#')[0].split()
    if not w:
        continue
    k = 0
    for c in (w[1] if len(w) > 1 else '-'):
        k |= KEYS.get(c, 0)
    m += [k] * int(w[0])
s = sorted(int(v) for v in snaps.split(',') if v.strip())
# the route's header lines (test/host/playhost.c --nodark / --global / --room; tools/tracer.py TRACE_*)
hdr = {}
for line in open(path):
    w = line.split()
    if len(w) >= 3 and w[0] == '#' and w[1] in ('nodark', 'globals', 'room'):
        hdr.setdefault(w[1], w[2])
KNOWN = {'madeMoai', 'kaliPunish', 'arrows', 'bombs', 'rope', 'plife', 'money', 'hasJetpack', 'hasCape',
         'hasParachute', 'hasMitt', 'hasGloves', 'hasSpringShoes', 'hasSpikeShoes', 'hasKapala', 'hasAnkh',
         'hasCompass', 'hasStickyBombs', 'hasUdjatEye', 'hasCrown', 'hasJordans', 'lake', 'cityOfGold', 'pickupItem'}
for kv in hdr.get('globals', '').split(','):
    if kv and kv.split('=')[0] not in KNOWN:
        sys.exit(f'mkroute.py: {path}: global {kv} not known to src/main/game.c')
ROOMS = {'rLevel': 0, 'rLevel2': 1, 'rLevel3': 2, 'rOlmec': 3}   # gen_room_for_level's numbers
if hdr.get('room', 'rLevel') not in ROOMS:
    sys.exit(f'mkroute.py: {path}: room {hdr["room"]} not known (rLevel, rLevel2, rLevel3, rOlmec)')
L = ['/* generated by tests/game/mkroute.py: do not edit */', f'/* {path} */',
     f'#define ROUTE_SEED {int(seed)}u', f'#define ROUTE_LEVEL {int(level)}', f'#define ROUTE_MONEY {int(money)}',
     f'#define ROUTE_ENEMIES {int(enemies)}', f'#define ROUTE_TAIL {int(tail)}', f'#define ROUTE_N {len(m)}',
     f'#define ROUTE_NODARK {int(hdr.get("nodark", -1))}', f'#define ROUTE_ROOM {ROOMS[hdr.get("room", "rLevel")]}',
     '#define ROUTE_GLOBALS ' + ('"%s"' % hdr['globals'] if 'globals' in hdr else '0'),
     f'static const uint16_t route_keys[{max(len(m), 1)}] = {{']
for i in range(0, len(m), 16):
    L.append('    ' + ', '.join(str(v) for v in m[i:i + 16]) + ',')
L += ['};', f'#define NSNAPS {len(s)}', f'static const int32_t snaps[{max(len(s), 1)}] = {{ ' +
      ', '.join(str(v) for v in s or [-1]) + ' };', '']
open(out, 'w').write('\n'.join(L))
