#!/usr/bin/env python3
"""tests/game's route: the key masks of a route file (as test/host/playhost.c parses it), its seed / level / money /
enemies, and the records whose frames are held for snapshots.
    mkroute.py <out.h> <route.txt> <seed> <level> <money> <enemies> <tail> "<rec,rec,...>" """
import sys

KEYS = dict(R=1, L=2, U=4, D=8, J=16, A=32, I=64, N=128, B=256, O=512, F=1024, P=2048, S=4096)
out, path, seed, level, money, enemies, tail, snaps = sys.argv[1:9]
m = []
for line in open(path):
    w = line.split('#')[0].split()
    if not w:
        continue
    k = 0
    for c in (w[1] if len(w) > 1 else '-'):
        k |= KEYS.get(c, 0)
    m += [k] * int(w[0])
s = sorted(int(v) for v in snaps.split(',') if v.strip())
L = ['/* generated by tests/game/mkroute.py: do not edit */', f'/* {path} */',
     f'#define ROUTE_SEED {int(seed)}u', f'#define ROUTE_LEVEL {int(level)}', f'#define ROUTE_MONEY {int(money)}',
     f'#define ROUTE_ENEMIES {int(enemies)}', f'#define ROUTE_TAIL {int(tail)}', f'#define ROUTE_N {len(m)}',
     f'static const uint16_t route_keys[{max(len(m), 1)}] = {{']
for i in range(0, len(m), 16):
    L.append('    ' + ', '.join(str(v) for v in m[i:i + 16]) + ',')
L += ['};', f'#define NSNAPS {len(s)}', f'static const int32_t snaps[{max(len(s), 1)}] = {{ ' +
      ', '.join(str(v) for v in s or [-1]) + ' };', '']
open(out, 'w').write('\n'.join(L))
