#!/usr/bin/env python3
"""tests/playsh2 job table: generation cases (seeds x levels), the P4 routes with their seeds (enemies removed,
level 1: scripts/p4_trace.sh) and every P5 route (enemies kept; seed, level and money from its "# seed / level /
money" lines: scripts/p5_trace.sh), the route files parsed as test/host/playhost.c does.
   mkjobs.py <out.h> [routes_dir]"""
import sys, os, glob, re

P4 = [("p4_exit559", 559), ("p4_hang_ladder", 1), ("p4_items", 1), ("p4_spikes", 58), ("p4_push_rope", 365),
      ("p1_walk", 1), ("p4_bomb_drop", 1), ("p4_bomb_throw", 7)]

def routes(rd):
    """(name, seed, level, money, enemies)"""
    out = [(n, s, 1, 0, 0) for n, s in P4]
    for f in sorted(glob.glob(os.path.join(rd, 'p5_*.txt'))):
        t = open(f).read()
        g = lambda k, d: int((re.search(r'^# *%s (\d+)' % k, t, re.M) or [None, d])[1])
        out.append((os.path.basename(f)[:-4], g('seed', 1), g('level', 1), g('money', 0), 1))
    return out
GEN_SEEDS = [120965577, 21187555, 1455299991]
GEN_LEVELS = list(range(1, 17))            # mines 1-4, lush 5-8, ice 9-12, temple 13-15, olmec 16
KEYS = dict(R=1, L=2, U=4, D=8, J=16, A=32, I=64, N=128, B=256, O=512, F=1024, P=2048, S=4096)

def masks(path):
    out = []
    for line in open(path):
        line = line.split('#')[0].split()
        if not line: continue
        n = int(line[0]); k = line[1] if len(line) > 1 else '-'
        m = 0
        for c in k: m |= KEYS.get(c, 0)
        out += [m] * n
    return out[:100000]

def main():
    out, rd = sys.argv[1], (sys.argv[2] if len(sys.argv) > 2 else '../routes')
    L = ['/* generated by tests/playsh2/mkjobs.py */', '#include "core.h"']
    R = routes(rd)
    for name, *_ in R:
        m = masks(os.path.join(rd, name + '.txt'))
        L.append('static const uint16_t m_%s[%d] = {' % (name, len(m)))
        for i in range(0, len(m), 16): L.append('    ' + ', '.join(str(v) for v in m[i:i + 16]) + ',')
        L.append('};')
    L.append('static const struct route routes[%d] = {' % len(R))
    for name, _, lv, money, en in R:
        L.append('    { "%s", m_%s, (int)(sizeof m_%s / 2), %d, %d, %d },' % (name, name, name, lv, money, en))
    L.append('};')
    jobs = [(s, lv, -1) for s in GEN_SEEDS for lv in GEN_LEVELS] + [(r[1], 0, k) for k, r in enumerate(R)]
    L.append('#define NJOBS %d' % len(jobs))
    L.append('static const struct job jobs[NJOBS] = {')
    for s, lv, r in jobs: L.append('    { %du, %d, %d },' % (s, lv, r))
    L.append('};')
    open(out, 'w').write('\n'.join(L) + '\n')

main()
