#!/usr/bin/env python3
"""tests/playsh2 job table: generation cases (seeds x levels), the P4 routes with their seeds (enemies removed,
level 1: scripts/p4_trace.sh) and every P5 route (enemies kept; seed, level and money from its "# seed / level /
money" lines: scripts/p5_trace.sh), the route files parsed as test/host/playhost.c does.
   mkjobs.py <out.h> [routes_dir] [--jt] [--routes a,b,...]
--routes: only those routes' jobs, in that order (no generation jobs; scripts/jtcost.sh)"""
import sys, os, glob, re

P4 = [("p4_exit559", 559), ("p4_hang_ladder", 1), ("p4_items", 1), ("p4_spikes", 58), ("p4_push_rope", 365),
      ("p1_walk", 1), ("p4_bomb_drop", 1), ("p4_bomb_throw", 7)]

def routes(rd):
    """(name, seed, level, money, enemies)"""
    out = [(n, s, 1, 0, 0) for n, s in P4]
    for f in sorted(glob.glob(os.path.join(rd, 'p5_*.txt'))):
        t = open(f).read()
        g = lambda k, d: int((re.search(r'^# *%s (\d+)' % k, t, re.M) or [None, d])[1])
        out.append((os.path.basename(f)[:-4], g('seed', 1), g('level', 1), g('money', 0), 1))
    return out
GEN_SEEDS = [120965577, 21187555, 1455299991]
GEN_LEVELS = list(range(1, 17))            # mines 1-4, lush 5-8, ice 9-12, temple 13-15, olmec 16
KEYS = dict(R=1, L=2, U=4, D=8, J=16, A=32, I=64, N=128, B=256, O=512, F=1024, P=2048, S=4096)

def masks(path):
    out = []
    for line in open(path):
        line = line.split('#')[0].split()
        if not line: continue
        n = int(line[0]); k = line[1] if len(line) > 1 else '-'
        m = 0
        for c in k: m |= KEYS.get(c, 0)
        out += [m] * n
    return out[:100000]

# --jt: one generation case per area and every route (all of it fits main RAM at PIN_MAX 1792, docs/DRAW.md section 6; host
# results equal to the unpatched build: scripts/playsh2_jt.sh checks it)
JT = '--jt' in sys.argv
JT_GEN = [(120965577, 2), (120965577, 6), (120965577, 10), (120965577, 14), (120965577, 16)]
JT_ROUTES = ['p4_exit559', 'p4_hang_ladder', 'p4_items', 'p4_spikes', 'p4_push_rope', 'p1_walk', 'p4_bomb_drop',
             'p4_bomb_throw', 'p5_buy', 'p5_caveman', 'p5_cavestun', 'p5_giant', 'p5_idol', 'p5_l3spider', 'p5_l4',
             'p5_shop', 'p5_snakes', 'p5_spider']     # the 18 of the first jtcps3 runs (screen: 23 rows)

def main():
    argv = sys.argv[1:]
    only = None
    if '--routes' in argv:
        k = argv.index('--routes'); only = argv[k + 1].split(','); del argv[k:k + 2]
    args = [a for a in argv if a != '--jt']
    out, rd = args[0], (args[1] if len(args) > 1 else '../routes')
    L = ['/* generated by tests/playsh2/mkjobs.py */', '#include "core.h"']
    R = routes(rd)
    for name, *_ in R:
        m = masks(os.path.join(rd, name + '.txt'))
        L.append('static const uint16_t m_%s[%d] = {' % (name, len(m)))
        for i in range(0, len(m), 16): L.append('    ' + ', '.join(str(v) for v in m[i:i + 16]) + ',')
        L.append('};')
    L.append('static const struct route routes[%d] = {' % len(R))
    for name, _, lv, money, en in R:
        L.append('    { "%s", m_%s, (int)(sizeof m_%s / 2), %d, %d, %d },' % (name, name, name, lv, money, en))
    L.append('};')
    jobs = [(s, lv, -1) for s in GEN_SEEDS for lv in GEN_LEVELS] + [(r[1], 0, k) for k, r in enumerate(R)]
    if JT:                                     # the jtcps3 variant: a few jobs that fit main RAM (scripts/playsh2_jt.sh)
        jobs = [(s, lv, -1) for s, lv in JT_GEN] + [(r[1], 0, k) for k, r in enumerate(R) if JT_ROUTES is None or r[0] in JT_ROUTES]
    if only is not None:                       # --routes: those routes only, in the order given
        names = [r[0] for r in R]
        bad = [n for n in only if n not in names]
        if bad: sys.exit('mkjobs.py: unknown route(s) %s' % ', '.join(bad))
        jobs = [(R[names.index(n)][1], 0, names.index(n)) for n in only]
    L.append('#define NJOBS %d' % len(jobs))
    L.append('static const struct job jobs[NJOBS] = {')
    for s, lv, r in jobs: L.append('    { %du, %d, %d },' % (s, lv, r))
    L.append('};')
    open(out, 'w').write('\n'.join(L) + '\n')

main()
