#!/usr/bin/env python3
"""tests/sndrules: script.txt -> the C table (build/script.h) main.c runs.  mkscript.py <script.txt> <script.h>"""
import sys

OPS = ['play', 'guard', 'music', 'aplay', 'stop', 'stopmusic', 'stopall', 'pause', 'resume', 'gain', 'level',
       'musicflag']


def parse(path):
    rows = []
    for line in open(path):
        w = line.split('#')[0].split()
        if not w:
            continue
        f, op, args = int(w[0]), w[1], w[2:]
        if op not in OPS:
            raise SystemExit(f'{path}: unknown op {op}')
        rows.append((f, op, args))
    if [r[0] for r in rows] != sorted(r[0] for r in rows):
        raise SystemExit(f'{path}: frames out of order')
    return rows


def main():
    rows = parse(sys.argv[1])
    out = ['/* generated by tests/sndrules/mkscript.py from script.txt */',
           'enum { ' + ', '.join(f'OP_{o.upper()}' for o in OPS) + ' };',
           'static const struct step { uint16_t frame; uint8_t op; int16_t s, a, b; } script[] = {']
    for f, op, args in rows:
        s = 'SND_' + args[0] if args and op != 'musicflag' else '0'
        nums = [int(a) for a in (args if op == 'musicflag' else args[1:])] + [0, 0]
        out.append(f'    {{ {f}, OP_{op.upper()}, {s}, {nums[0]}, {nums[1]} }},')
    out += ['};', f'#define SCRIPT_N {len(rows)}', f'#define SCRIPT_END {rows[-1][0]}']
    open(sys.argv[2], 'w').write('\n'.join(out) + '\n')


if __name__ == '__main__':
    main()
