#!/bin/sh
# tests/playsh2's jtcps3 variant (JT=1): 2 generation cases and 2 routes (p4_push_rope, p5_l3spider) that fit the
# CPS3's 512 KB of main RAM with PIN_MAX = INST_MAX = 790 and pcol.c's RT_NODES = 360 (no sprite or character RAM
# used as memory; the host check below shows the limits change nothing for these jobs); the program
# times them with the FRT and shows the results on screen in large text (sprite RAM self-test, per job total
# clocks, step mean / max, checksum OK against host values built in). This script: the host check that the patched
# limits change nothing for these jobs, the expected hashes, the build, a MAME run with a snapshot of the screen.
#   scripts/playsh2_jt.sh          -> tests/playsh2/build/jt/elf/mame/sfiii3na (the set), build/jt/out/{snap,jt.txt}
set -e
cd "$(dirname "$0")/.."
T=tests/playsh2; B=$T/build; J=$B/jt; O=$J/out; N=790; RT=${RT:-360}
rm -rf "$O" "$B/g" "$J/gA"; mkdir -p "$O/w" "$B/g" "$J/gA"
git archive "${GAME_REV:-HEAD}" src/game | tar -x -C "$J/gA" --strip-components=2
cp build/gen/objects.[ch] build/gen/gentables.[ch] build/gen/playtables.[ch] "$J/gA/"
cp "$J/gA"/* "$B/g/"
sed -i '' "s/^#define PIN_MAX 4096\$/#define PIN_MAX $N/" "$B/g/play.h"
sed -i '' "s/^#define INST_MAX 2048 .*/#define INST_MAX $N/" "$B/g/inst.h"
sed -i '' "s/^#define RT_NODES 640\$/#define RT_NODES $RT/" "$B/g/pcol.c"
grep -q "^#define PIN_MAX $N\$" "$B/g/play.h"; grep -q "^#define INST_MAX $N\$" "$B/g/inst.h"
grep -q "^#define RT_NODES $RT\$" "$B/g/pcol.c"; touch "$B/g/stamp"
python3 $T/mkjobs.py "$J/jobs.h" tests/routes --jt
# the host, unpatched (A) and with the limits (B): the same records, then the expected hashes
for v in A B; do
  G=$J/gA; [ $v = B ] && G=$B/g
  cc -std=c99 -O2 -ffp-contract=off -w -I$T -I$J -I$G -o "$J/host$v" $T/host.c $T/core.c $G/*.c -lm
done
NJ=$("$J/hostA" --count); j=0
{ echo "/* generated by scripts/playsh2_jt.sh: the host's hash of each job's records (main.c JT) */"
  echo "static const uint32_t jt_expect[$NJ] = {"; } > "$J/jt_expect.h"
while [ $j -lt $NJ ]; do
  [ "$("$J/hostA" $j | md5)" = "$("$J/hostB" $j | md5)" ] || { echo "job $j: the limits change the host's records"; exit 1; }
  echo "    $("$J/hostB" --jthash $j)," >> "$J/jt_expect.h"; j=$((j + 1))
done
{ echo "};"
  echo "#define JT_LABEL \"G:L2,L9 S120965577 R:P4_PUSH_ROPE,P5_L3SPIDER\""; } >> "$J/jt_expect.h"
scripts/dmake.sh $T OUT=build/jt/elf JT=1 SOFTFP=1 >/dev/null
PSH2_OUT="$O/jt.txt" PSH2_NJOBS=$NJ mame sfiii3na -rompath "$J/elf/mame" -skip_gameinfo -nothrottle -sound none \
  -video none -seconds_to_run 3000 -cfg_directory "$O/w/cfg" -nvram_directory "$O/w/nvram" -snapshot_directory "$O/snap" \
  -diff_directory "$O/w/diff" -state_directory "$O/w/sta" -inipath "$O/w" -autoboot_script scripts/lua/playsh2_jt.lua \
  >"$O/mame.log" 2>&1 || true
rm -rf "$O/w"
cat "$J/jt_expect.h" | grep 0x
cat "$O/jt.txt"
ls "$O/snap"/*/*.png 2>/dev/null || ls -R "$O/snap"
