#!/bin/sh
# tests/playsh2's jtcps3 variant (JT=1): one generation case per area and all 18 routes in the CPS3's 512 KB of main
# RAM with PIN_MAX 1000 (since e380bb6 everything fits; no sprite or character RAM used as memory; the host check
# below shows the limit changes nothing for these jobs); the program times them with the FRT and shows the results
# on screen (large: PASS n/N and the sprite RAM self-test; a table: per job total clocks, step mean / max, checksum
# OK against host values built in). This script: the host check that the patched
# limits change nothing for these jobs, the expected hashes, the build, a MAME run with a snapshot of the screen.
#   scripts/playsh2_jt.sh          -> tests/playsh2/build/jt/elf/mame/sfiii3na (the set), build/jt/out/{snap,jt.txt}
set -e
cd "$(dirname "$0")/.."
T=tests/playsh2; B=$T/build; J=$B/jt; V=${JTV:-}; O=$J/out$V; N=${PIN:-1000}
rm -rf "$O" "$B/g" "$J/gA"; mkdir -p "$O/w" "$B/g" "$J/gA"
git archive "${GAME_REV:-HEAD}" src/game | tar -x -C "$J/gA" --strip-components=2
cp build/gen/objects.[ch] build/gen/gentables.[ch] build/gen/playtables.[ch] "$J/gA/"
# EXACT=1: the exact build (PCOL_EXACT); default the shipping build's collision grid. GRID_SHIFT=<n>: 2^n px cells
if [ "${EXACT:-0}" = 1 ]; then { echo "#define PCOL_EXACT 1"; cat "$J/gA/pcol.c"; } > "$J/pcol.tmp" && mv "$J/pcol.tmp" "$J/gA/pcol.c"; fi
if [ -n "${GRID_SHIFT:-}" ]; then { echo "#define PCOL_GRID_SHIFT $GRID_SHIFT"; cat "$J/gA/pcol.c"; } > "$J/pcol.tmp" && mv "$J/pcol.tmp" "$J/gA/pcol.c"; fi
cp "$J/gA"/* "$B/g/"
sed -i '' "s/^#define PIN_MAX 4096\$/#define PIN_MAX $N/" "$B/g/play.h"
grep -q "^#define PIN_MAX $N\$" "$B/g/play.h"; touch "$B/g/stamp"
# snapcfg.h (tests/playsh2/core.c): where the snapshot keeps alpha
sed -n '/^struct pin_ext {/,/^};/p' "$B/g/play.h" | grep -q "alpha" && echo "#define ALPHA_IN_EXT 1" > "$B/g/snapcfg.h" || : > "$B/g/snapcfg.h"
cp "$B/g/snapcfg.h" "$J/gA/"
python3 $T/mkjobs.py "$J/jobs.h" tests/routes --jt
# the host, unpatched (A) and with the limits (B): the same records, then the expected hashes
for v in A B; do
  G=$J/gA; [ $v = B ] && G=$B/g
  cc -std=c99 -O2 -ffp-contract=off -w -I$T -I$J -I$G -o "$J/host$v" $T/host.c $T/core.c $T/sndstub.c src/snd/snd.c -Isrc/snd -Isrc/front -I../cps3-testgame/sdk/include $G/*.c -lm
done
NJ=$("$J/hostA" --count); j=0
{ echo "/* generated by scripts/playsh2_jt.sh: the host's hash of each job's records (main.c JT) */"
  echo "static const uint32_t jt_expect[$NJ] = {"; } > "$J/jt_expect.h"
while [ $j -lt $NJ ]; do
  # since slot reuse (286acc7) the checksum covers the slot layout (PW.n, slot order), which depends on PIN_MAX
  # (pw_release's batching): a difference is reported, not fatal (STRICT=1: fatal); the expected hashes are hostB's
  [ "$("$J/hostA" $j | md5)" = "$("$J/hostB" $j | md5)" ] || { echo "job $j: the limits change the host's records (slot layout)"; [ "${STRICT:-0}" = 1 ] && exit 1; }
  echo "    $("$J/hostB" --jthash $j)," >> "$J/jt_expect.h"; j=$((j + 1))
done
{ echo "};"
  echo "#define JT_LABEL \"\""; } >> "$J/jt_expect.h"
# JTV=<name>: a code-layout variant (build/jt/elf<name>, out<name>): OSFILES (-Os files), LAYOUT=1 (mklayout.py
# from tests/playsh2/hot.txt)
LO=; [ "${LAYOUT:-0}" = 1 ] && { python3 $T/mklayout.py $T/hot.txt $J/link$V.ld; LO=LAYOUT=build/jt/link$V.ld; }
VN=$(echo "${V:-BASE}" | tr a-z_ A-Z-)
scripts/dmake.sh $T OUT=build/jt/elf$V JT=1 SOFTFP=1 OSFILES="${OSFILES:-}" $LO JTNAME=$VN >/dev/null
scripts/dmake.sh $T OUT=build/jt/elf$V JT=1 SOFTFP=1 OSFILES="${OSFILES:-}" $LO JTNAME=$VN PROG=pjt$V \
  TITLE="Spelunky SH-2 timing $VN" mister >/dev/null
PSH2_OUT="$O/jt.txt" PSH2_NJOBS=$NJ scripts/mame.sh sfiii3na -rompath "$J/elf$V/mame" -skip_gameinfo -nothrottle -sound none \
  -video none -seconds_to_run 3000 -cfg_directory "$O/w/cfg" -nvram_directory "$O/w/nvram" -snapshot_directory "$O/snap" \
  -diff_directory "$O/w/diff" -state_directory "$O/w/sta" -inipath "$O/w" -autoboot_script scripts/lua/playsh2_jt.lua \
  >"$O/mame.log" 2>&1 || true
rm -rf "$O/w"
cat "$J/jt_expect.h" | grep 0x
cat "$O/jt.txt"
ls "$O/snap"/*/*.png 2>/dev/null || ls -R "$O/snap"
