#!/usr/bin/env python3
"""src/draw tables (build/gen/drawtab.{c,h}) from build/gen (gentables.h, sprites.h, objects.c) and HD's object
events (refs/hd/src/objects/*/Draw_0.gml):

    tools/drawtables.py <hd src> <gen dir>

  draw_spr[GSPR_*]   the play code's sprite (gentables.h, GSPR_*) as tools/hdsprites.py's (sprites.h, SPR_*), by
                     name; -1 for sprites sprite_add'ed at run time (no art)
  draw_kind[OBJ_*]   how an instance is drawn: the Draw event that applies to it (its own or the nearest parent's;
                     GameMaker runs the parent's event when the object has none), DK_SELF when no ancestor has one
                     (the default draw: draw_self), plus DK_SOLID (bit 7) for the oSolid family (terrain cells)
"""
import glob
import os
import re
import sys

# the objects with a Draw event (refs/hd/src/objects/<o>/Draw_0.gml) and how src/draw handles them
KIND = {
    'oPlayer1': 'DK_PLAYER',      # characterDrawEvent
    'oEnemy': 'DK_ENEMY',         # mirrored at x + 16 by facing
    'oShopkeeper': 'DK_SHOP',     # oEnemy's + the shotgun
    'oDamsel': 'DK_DAMSEL',       # image_xscale by facing (set by the play code's ev_draw), price tag
    'oItem': 'DK_ITEM',           # unmirrored, image_index, price tag
    'oArrow': 'DK_PLAIN',         # draw_sprite_ext(.., 1, 1, image_angle): angle not drawn (no rotation)
    'oEntrance': 'DK_PLAIN',      # draw_sprite(sprite_index, -1, x, y)
    'oExit': 'DK_PLAIN',
    'oTombLord': 'DK_PLAIN',      # draw_sprite_ext(.., 1, image_yscale, ..)
    'oYetiKing': 'DK_PLAIN',
    'oDice': 'DK_DICE',           # draw_self + sRedArrowDown while betting
    'oPDummy': 'DK_PDUMMY',       # the transition room's player
    'oPDummy2': 'DK_PDUMMY',
    'oJaws': 'DK_JAWS',
    'oLevel': 'DK_NONE',          # the dark-level rectangle (draw.c draws it from global.darkLevel)
    'oMsgSign': 'DK_NONE',        # empty Draw event: draws nothing
    'oIntro': 'DK_FRONT',         # src/front draws it (the fade rectangle, the story text)
    'oPDummy3': 'DK_PDUMMY',      # the intro's actor: oPDummy's drawing (image_xscale from facing; no jetpack / item)
}
# Draw events not translated (not in the mines play rooms): drawn as draw_self and counted (draw_stats.todo)
TODO = 'DK_TODO'


def enum_names(path, prefix, end):
    t = open(path).read()
    return re.findall(r'^\s+%s(\w+),' % prefix, t[:t.index(end)], re.M)


def main():
    src, gen = sys.argv[1], sys.argv[2]
    gspr = enum_names(os.path.join(gen, 'gentables.h'), 'GSPR_', 'GSPR_COUNT')
    spr = enum_names(os.path.join(gen, 'sprites.h'), 'SPR_', 'SPR_COUNT')
    sid = {n: i for i, n in enumerate(spr)}
    oc = open(os.path.join(gen, 'objects.c')).read()
    body = oc[oc.index('objdefs[OBJ_COUNT] = {'):]
    body = body[:body.index('\n};')]
    objs = re.findall(r'\{ "(\w+)", (OBJ_\w+|-1|OBJ_NONE)', body)
    parent = {o: (p[4:] if p.startswith('OBJ_') else None) for o, p in objs}
    has = {os.path.basename(os.path.dirname(f)) for f in glob.glob(os.path.join(src, 'objects', '*', 'Draw_0.gml'))}

    def owner(o):
        while o:
            if o in has:
                return o
            o = parent.get(o)
        return None

    def is_a(o, a):
        while o:
            if o == a:
                return True
            o = parent.get(o)
        return False

    kinds, todo = [], set()
    for o, _ in objs:
        w = owner(o)
        k = 'DK_SELF' if w is None else KIND.get(w, TODO)
        if k == TODO:
            todo.add(w)
        kinds.append(k + (' | DK_SOLID' if is_a(o, 'oSolid') else ''))
    missing = [n for n in gspr if n not in sid]
    H = ['/* generated by tools/drawtables.py: do not edit */', '#ifndef DRAWTAB_H', '#define DRAWTAB_H',
         '#include <stdint.h>',
         'enum draw_kind { DK_SELF, DK_NONE, DK_PLAYER, DK_ENEMY, DK_SHOP, DK_DAMSEL, DK_ITEM, DK_PLAIN, DK_DICE,',
         '                 DK_PDUMMY, DK_JAWS, DK_TODO, DK_FRONT };',
         '#define DK_SOLID 0x80u',
         f'extern const int16_t draw_spr[{len(gspr)}];     /* GSPR_* -> SPR_* (-1: no art) */',
         f'extern const uint8_t draw_kind[{len(objs)}];    /* OBJ_* -> enum draw_kind | DK_SOLID */',
         '/* the Draw events drawn as draw_self for now (DK_TODO): ' + ' '.join(sorted(todo)) + ' */',
         '#endif', '']
    C = ['/* generated by tools/drawtables.py: do not edit */', '#include "drawtab.h"',
         f'const int16_t draw_spr[{len(gspr)}] = {{']
    for k in range(0, len(gspr), 12):
        C.append('    ' + ' '.join('%d,' % sid.get(n, -1) for n in gspr[k:k + 12]))
    C += ['};', f'const uint8_t draw_kind[{len(objs)}] = {{']
    for (o, _), k in zip(objs, kinds):
        C.append(f'    {k},  /* {o} */')
    C += ['};', '']
    open(os.path.join(gen, 'drawtab.h'), 'w').write('\n'.join(H))
    open(os.path.join(gen, 'drawtab.c'), 'w').write('\n'.join(C))
    print(f'drawtab: {len(gspr)} sprites ({len(missing)} without art: {" ".join(missing)}), {len(objs)} objects, '
          f'Draw events not translated: {" ".join(sorted(todo))}')


if __name__ == '__main__':
    main()
