#!/usr/bin/env python3
"""The front end's room tables (src/front): rIntro, rTitle, rHighscores and the ending's rEnd, rEnd2, rEnd3, rCredits2
from HD 1.2.2's data file (game.unx, read by
UndertaleModTool's CLI in Docker, as tools/hdplaytables.py reads the transition rooms): every room instance in the
data file's creation order with its runtime id, object, x, y, scale and its layer's depth, the creation code (as
text, translated by hand in src/front), and the room's background layers.

    tools/fronttables.py <game.unx> <gen dir>        -> <gen dir>/fronttables.{h,c} (+ fronttables_rt.txt)
"""
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import hdplaytables  # noqa: E402

ROOMS = ['rIntro', 'rTitle', 'rHighscores', 'rEnd', 'rEnd2', 'rEnd3', 'rCredits2']
CSX = r'''
using System.IO;
using System.Text;
var sb = new StringBuilder();
foreach (var name in new[]{ROOMS}) {
    var r = Data.Rooms.ByName(name);
    sb.Append($"ROOM {name} {r.Width} {r.Height} {r.Speed}\n");
    var depth = new System.Collections.Generic.Dictionary<uint, int>();
    var lpos = new System.Collections.Generic.Dictionary<uint, int>();
    foreach (var L in r.Layers) {
        if (L.InstancesData != null) {
            int lp = 0;
            foreach (var o in L.InstancesData.Instances) { depth[o.InstanceID] = L.LayerDepth; lpos[o.InstanceID] = lp++; }
        }
        if (L.AssetsData != null && L.AssetsData.LegacyTiles != null)
            foreach (var t in L.AssetsData.LegacyTiles)
                sb.Append($"TILE {(t.spriteMode ? t.SpriteDefinition.Name.Content : t.BackgroundDefinition.Name.Content)} {t.SourceX} {t.SourceY} {t.Width} {t.Height} {t.X} {t.Y} {L.LayerDepth}\n");
        if (L.BackgroundData != null) {
            var b = L.BackgroundData;
            sb.Append($"BG {L.LayerName.Content} {L.LayerDepth} {(b.Sprite == null ? "-" : b.Sprite.Name.Content)} {(b.Visible?1:0)} {(b.TiledHorizontally?1:0)} {(b.TiledVertically?1:0)} {(b.Stretch?1:0)} {L.XOffset} {L.YOffset} {L.HSpeed} {L.VSpeed} {b.Color}\n");
        }
    }
    foreach (var o in r.GameObjects)
        sb.Append($"INST {o.InstanceID} {o.ObjectDefinition.Name.Content} {o.X} {o.Y} {o.ScaleX} {o.ScaleY} {o.Rotation} {(o.CreationCode == null ? "-" : o.CreationCode.Name.Content)} {depth[o.InstanceID]} {lpos[o.InstanceID]}\n");
}
File.WriteAllText("OUT", sb.ToString());
'''.replace('ROOMS', ','.join('"' + r + '"' for r in ROOMS))


def export(unx, work):
    unx, work = os.path.abspath(unx), os.path.abspath(work)
    root = os.path.commonpath([unx, hdplaytables.UTMT, work])
    rel = lambda p: '/w/' + os.path.relpath(p, root)
    txt = os.path.join(work, 'fronttables_rt.txt')
    csx = os.path.join(work, 'fronttables_rt.csx')
    open(csx, 'w').write(CSX.replace('OUT', rel(txt)))
    if os.path.exists(txt):
        os.remove(txt)
    r = subprocess.run(['docker', 'run', '--rm', '-v', f'{root}:/w', hdplaytables.DOTNET, 'dotnet',
                        rel(hdplaytables.UTMT), 'load', rel(unx), '-s', rel(csx)], capture_output=True, text=True)
    if not os.path.exists(txt):
        sys.exit(r.stdout[-3000:] + r.stderr[-3000:])
    return txt


def write(txt, gen):
    rooms, cur = {}, None
    for line in open(txt):
        f = line.split()
        if f[0] == 'ROOM':
            cur = rooms[f[1]] = dict(w=int(f[2]), h=int(f[3]), insts=[], bg=None, tiles=[])
        elif f[0] == 'TILE':
            cur['tiles'].append((f[1],) + tuple(int(v) for v in f[2:9]))
        elif f[0] == 'BG' and f[3] != '-':
            cur['bg'] = f[3]
        elif f[0] == 'INST':
            sx, sy, rot = float(f[5]), float(f[6]), float(f[7])
            if rot != 0 or sy != 1:
                sys.exit(f'room instance with rotation / y scale: {line}')
            cur['insts'].append((int(f[1]), f[2], int(float(f[3])), int(float(f[4])), int(f[9]), sx, f[8], int(f[10])))
    H = ['/* generated by tools/fronttables.py from HD 1.2.2 (game.unx): do not edit */', '#ifndef FRONTTABLES_H',
         '#define FRONTTABLES_H', '#include <stdint.h>',
         '/* a room instance in creation order: runtime id, object, position, its layer\'s depth, image_xscale (only the',
         '   title\'s widescreen padding blocks are not 1), creation code (an index src/front translates; -1 none) */',
         '/* lpos: the instance\'s place in its layer (the runner draws a layer\'s instances from its last: equal depths',
         '   later in the layer first; instances made at run time before all of them, newest first) */',
         'struct frinst { int32_t id; int16_t obj; int16_t x, y; int32_t depth; float xscale; int8_t cc; int16_t lpos; };',
         '/* a room\'s own tile layers (legacy tiles): background, source rectangle, position, layer depth */',
         'struct frtile { int16_t bg, left, top, w, h, x, y; int32_t depth; };',
         'struct froom { int16_t w, h; int16_t n; const struct frinst *in; int16_t bg; int16_t nt; const struct frtile *t; };']
    C = ['/* generated by tools/fronttables.py from HD 1.2.2 (game.unx): do not edit */', '#include "objects.h"',
         '#include "gentables.h"', '#include "fronttables.h"']
    ccs = []
    for rn, r in rooms.items():
        H.append(f'extern const struct froom froom_{rn};  /* {len(r["insts"])} instances */')
        C.append(f'static const struct frinst froom_{rn}_in[{len(r["insts"])}] = {{')
        for iid, obj, x, y, depth, sx, cc, lp in r['insts']:
            k = -1
            if cc != '-':
                ccs.append(cc)
                k = len(ccs) - 1
            C.append(f'    {{ {iid}, OBJ_{obj}, {x}, {y}, {depth}, {sx}f, {k}, {lp} }},')
        C += ['};', f'static const struct frtile froom_{rn}_t[{max(1, len(r["tiles"]))}] = {{']
        C += [f'    {{ GSPR_{t[0]}, {t[1]}, {t[2]}, {t[3]}, {t[4]}, {t[5]}, {t[6]}, {t[7]} }},' for t in r['tiles']] or ['    { 0 }']
        C += ['};', f'const struct froom froom_{rn} = {{ {r["w"]}, {r["h"]}, {len(r["insts"])}, froom_{rn}_in, '
              f'{"GSPR_" + r["bg"] if r["bg"] else -1}, {len(r["tiles"])}, froom_{rn}_t }};', '']
    H += [f'#define FRONT_CC_{c.replace("gml_RoomCC_", "")} {k}' for k, c in enumerate(ccs)]
    H += ['#endif', '']
    open(os.path.join(gen, 'fronttables.h'), 'w').write('\n'.join(H))
    open(os.path.join(gen, 'fronttables.c'), 'w').write('\n'.join(C))
    print('fronttables: ' + ', '.join(f'{rn} {len(r["insts"])} (+{len(r["tiles"])} tiles)' for rn, r in rooms.items()) + f'; creation code {ccs}')


if __name__ == '__main__':
    gen = sys.argv[2]
    txt = os.path.join(gen, 'fronttables_rt.txt')
    if '--no-export' not in sys.argv or not os.path.exists(txt):
        txt = export(sys.argv[1], gen)
    write(txt, gen)
