#!/usr/bin/env python3
"""Tables for the level generator (src/game/gen*.c), from HD 1.2.2's data file and GML.

    tools/hdgentables.py <hd src dir> <game.unx> <out gentables.h>      (also writes gentables.c next to it)

1. Sprite collision data, from the runtime's data file (game.unx, read by UndertaleModTool's CLI in Docker, as
   tools/tracer.py does): per sprite in the data file's order (= the runtime's sprite_index), the origin, the
   bounding box (margins, inclusive) and the separation-mask kind (0 rectangle, 1 precise, 2 rotated). enum gspr:
   GSPR_<name> = the runtime sprite index. Precise masks are not exported: every collision function the generator
   calls passes prec = 0 (bounding boxes only), see src/game/inst.c.
2. Room templates of scrRoomGen (the mines): the string literals of each `switch` block, in source order, taken
   from the GML lines given in ROOMGEN below (the control flow that picks them is hand-translated in
   src/game/genroom.c with the same line references).
3. gobjspr[OBJ_COUNT]: each object's default sprite_index (GSPR_*, -1 none), in build/gen/objects.h's object
   order (tools/hdobjects.py: the project's objects sorted by name).
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
UTMT = os.path.normpath(os.path.join(HERE, '..', '..', '_tools', 'UndertaleModTool', 'out-cli', 'UndertaleModCli.dll'))
DOTNET = 'mcr.microsoft.com/dotnet/sdk:10.0'

# name, first and last GML line (scripts/scrRoomGen/scrRoomGen.gml), strings per entry
ROOMGEN = [
    ('mines_start', 60, 68, 1),      # start room, cases 1..8
    ('mines_end', 77, 83, 1),        # end room, cases 1..6
    ('mines_side', 107, 120, 1),     # side room, cases 1..11
    ('mines_main', 129, 150, 1),     # path 0/1 main room, cases 1..12 (8 and 12: two strings each)
    ('mines_main3', 159, 171, 1),    # path 3, cases 1..8 (8: two strings)
    ('mines_shop', 176, 203, 1),     # shop: 176 base, 186 craps, 187 kissing (path 4); 192, 202, 203 (path 5)
    ('mines_snake', 210, 217, 1),    # snake pit middle (210), bottom (217)
    ('mines_drop', 227, 238, 1),     # drop, cases 1..12
    ('mines_obs8', 256, 263, 3),     # obstacle "8", cases 1..8 (strObs1..3)
    ('mines_obs5', 270, 285, 3),     # obstacle "5", cases 1..16
    ('mines_obs6', 292, 301, 3),     # obstacle "6", cases 1..10
]

CSX = r'''
using System.IO;
using System.Text;
var sb = new StringBuilder();
foreach (var s in Data.Sprites)
    sb.Append($"{s.Name.Content} {s.OriginX} {s.OriginY} {s.MarginLeft} {s.MarginTop} {s.MarginRight} {s.MarginBottom} {(int)s.SepMasks} {s.CollisionMasks.Count}\n");
File.WriteAllText("OUT", sb.ToString());
'''


def sprites(unx, work):
    unx, work = os.path.abspath(unx), os.path.abspath(work)
    root = os.path.commonpath([unx, UTMT, work])
    rel = lambda p: '/w/' + os.path.relpath(p, root)
    txt = os.path.join(work, 'gentables_sprites.txt')
    csx = os.path.join(work, 'gentables_sprites.csx')
    open(csx, 'w').write(CSX.replace('OUT', rel(txt)))
    r = subprocess.run(['docker', 'run', '--rm', '-v', f'{root}:/w', DOTNET, 'dotnet', rel(UTMT), 'load', rel(unx),
                        '-s', rel(csx)], capture_output=True, text=True)
    if not os.path.exists(txt):
        sys.exit(r.stdout[-3000:] + r.stderr[-3000:])
    out = []
    for line in open(txt):
        f = line.split()
        out.append((f[0], *map(int, f[1:])))
    return out


def roomgen(src):
    lines = open(os.path.join(src, 'scripts', 'scrRoomGen', 'scrRoomGen.gml')).read().split('\n')
    tabs = []
    for name, a, b, per in ROOMGEN:
        strs = []
        for ln in range(a, b + 1):
            for m in re.finditer(r'"([^"]*)"', lines[ln - 1]):
                s = m.group(1)
                if len(s) == (80 if per == 1 else 5):
                    strs.append((ln, s))
        tabs.append((name, per, strs))
    return tabs


def main():
    src, unx, out = sys.argv[1:4]
    os.makedirs(os.path.dirname(out) or '.', exist_ok=True)
    spr = sprites(unx, os.path.dirname(out) or '.')
    hdr = '/* generated by tools/hdgentables.py from HD 1.2.2 (game.unx, scrRoomGen.gml): do not edit */'
    h = [hdr, '#ifndef GENTABLES_H', '#define GENTABLES_H', '#include <stdint.h>', '', 'enum gspr {']
    h += [f'    GSPR_{s[0]},' for s in spr]
    h += ['    GSPR_COUNT', '};', '',
          '/* origin, bounding box (inclusive margins), mask kind: 0 rectangle, 1 precise, 2 rotated */',
          'struct gsprcol { int8_t xo, yo; int16_t l, t, r, b; uint8_t kind; };',
          'extern const struct gsprcol gsprcol[GSPR_COUNT];', 'extern const char *const gsprname[GSPR_COUNT];', '']
    c = [hdr, '#include "gentables.h"', '', 'const struct gsprcol gsprcol[GSPR_COUNT] = {']
    for s in spr:
        name, xo, yo, l, t, r, b, kind, nm = s
        c.append(f'    {{ {xo}, {yo}, {l}, {t}, {r}, {b}, {kind} }},  /* {name} */')
    c += ['};', '', 'const char *const gsprname[GSPR_COUNT] = {']
    c += [f'    "{s[0]}",' for s in spr]
    c += ['};', '']
    for name, per, strs in roomgen(src):
        n = len(strs)
        h.append(f'/* scrRoomGen.gml lines {strs[0][0]}-{strs[-1][0]}: {n} strings */')
        h.append(f'extern const char *const {name}[{n}];')
        c.append(f'const char *const {name}[{n}] = {{')
        c += [f'    "{s}",  /* :{ln} */' for ln, s in strs]
        c += ['};', '']
    objs = sorted(o for o in os.listdir(os.path.join(src, 'objects'))
                  if os.path.exists(os.path.join(src, 'objects', o, o + '.yy')))
    sidx = {n[0]: i for i, n in enumerate(spr)}
    h.append(f'#define GOBJ_COUNT {len(objs)}')
    h.append('extern const int16_t gobjspr[GOBJ_COUNT];  /* default sprite_index per object (objects.h order) */')
    c.append('const int16_t gobjspr[GOBJ_COUNT] = {')
    for o in objs:
        t = open(os.path.join(src, 'objects', o, o + '.yy'), encoding='utf-8-sig').read()
        m = re.search(r'"spriteId":\s*\{\s*"name":\s*"(\w+)"', t)
        c.append(f'    {sidx[m.group(1)] if m else -1},  /* {o}{" " + m.group(1) if m else ""} */')
    c += ['};', '']
    h += ['', '#endif', '']
    open(out, 'w').write('\n'.join(h))
    open(os.path.splitext(out)[0] + '.c', 'w').write('\n'.join(c))


if __name__ == '__main__':
    main()
