#!/usr/bin/env python3
"""HD 1.2.2's object and room tables for the C port, from the GameMaker project's .yy files (refs/hd/src).

    tools/hdobjects.py <hd src dir> <out objects.h> [--report]      (also writes objects.c next to it)

objects.h: enum obj (OBJ_<name>, in the project's object order, sorted by name), and per object its parent, sprite
name, solid / visible / persistent flags, the event list (type, number), and the ancestor table (obj_is[a][b]: a is b
or a child of b, as GameMaker's object matching: collision_point(..., oSolid) matches every child of oSolid).
Rooms: each room's instances in creation order (object, x, y, scale, creation code file name).
"""
import json
import os
import re
import sys

EVTYPE = {0: 'CREATE', 1: 'DESTROY', 2: 'ALARM', 3: 'STEP', 4: 'COLLISION', 5: 'KEYBOARD', 6: 'MOUSE', 7: 'OTHER',
          8: 'DRAW', 9: 'KEYPRESS', 10: 'KEYRELEASE', 12: 'CLEANUP', 13: 'GESTURE'}


def load_yy(path):
    t = open(path, encoding='utf-8-sig').read()
    t = re.sub(r',(\s*[}\]])', r'\1', t)          # trailing commas
    return json.loads(t)


def main():
    src, out = sys.argv[1], sys.argv[2]
    objs = {}
    for name in sorted(os.listdir(os.path.join(src, 'objects'))):
        y = os.path.join(src, 'objects', name, name + '.yy')
        if os.path.exists(y):
            objs[name] = load_yy(y)
    names = sorted(objs)
    idx = {n: i for i, n in enumerate(names)}

    def parent(n):
        p = objs[n].get('parentObjectId')
        return p['name'] if p else None

    hdr = '/* generated by tools/hdobjects.py from refs/hd/src (Spelunky Classic HD 1.2.2): do not edit */'
    lines = [hdr, '#ifndef OBJECTS_H', '#define OBJECTS_H', '#include <stdint.h>', '', 'enum obj {']
    lines += [f'    OBJ_{n},' for n in names]
    lines += ['    OBJ_COUNT', '};', '#define OBJ_NONE (-1)', '',
              'struct objdef {', '    const char *name;', '    int16_t parent;', '    const char *sprite;',
              '    const char *mask;', '    uint8_t solid, visible, persistent;', '};', '']
    c = [hdr, '#include "objects.h"', '', 'const struct objdef objdefs[OBJ_COUNT] = {']
    for n in names:
        o = objs[n]
        p = parent(n)
        spr = o.get('spriteId')
        msk = o.get('spriteMaskId')
        c.append(f'    {{ "{n}", {("OBJ_" + p) if p else "OBJ_NONE"}, '
                     f'{chr(34) + spr["name"] + chr(34) if spr else "0"}, '
                     f'{chr(34) + msk["name"] + chr(34) if msk else "0"}, '
                     f'{int(o.get("solid", False))}, {int(o.get("visible", True))}, {int(o.get("persistent", False))} }},')
    c += ['};', '']
    # ancestor table as bit rows: obj_is(a, b)
    words = (len(names) + 31) // 32
    lines += [f'#define OBJ_WORDS {words}', 'extern const struct objdef objdefs[OBJ_COUNT];',
              'extern const uint32_t obj_anc[OBJ_COUNT][OBJ_WORDS];']
    c += ['const uint32_t obj_anc[OBJ_COUNT][OBJ_WORDS] = {']
    for n in names:
        bits = [0] * words
        a = n
        while a:
            bits[idx[a] // 32] |= 1 << (idx[a] % 32)
            a = parent(a)
        c.append('    { ' + ', '.join(f'0x{b:08x}u' for b in bits) + ' },')
    c += ['};', '']
    lines += ['/* a is b or a descendant of b (GameMaker object matching) */',
              'static inline int obj_is(int a, int b) { return (obj_anc[a][b >> 5] >> (b & 31)) & 1; }', '']
    # rooms
    rooms = sorted(os.listdir(os.path.join(src, 'rooms')))
    lines.append('struct roominst { int16_t obj; int16_t x, y; const char *code; };')
    for r in rooms:
        ry = load_yy(os.path.join(src, 'rooms', r, r + '.yy'))
        byname = {}
        for L in ry.get('layers', []):
            for i in L.get('instances', []) or []:
                byname[i['name']] = i
        order = [c['name'] for c in ry.get('instanceCreationOrder', [])]
        lines.append(f'extern const struct roominst room_{r}[];')
        c.append(f'const struct roominst room_{r}[] = {{')
        for nm in order:
            i = byname[nm]
            code = i.get('hasCreationCode') and f'"{nm}"' or '0'
            c.append(f'    {{ OBJ_{i["objectId"]["name"]}, {int(i["x"])}, {int(i["y"])}, {code} }},')
        c.append('    { OBJ_NONE, 0, 0, 0 }')
        c.append('};')
    lines += ['', '#endif', '']
    os.makedirs(os.path.dirname(out) or '.', exist_ok=True)
    open(out, 'w').write('\n'.join(lines))
    open(os.path.splitext(out)[0] + '.c', 'w').write('\n'.join(c) + '\n')
    if '--report' in sys.argv:
        ev = {}
        for n in names:
            for e in objs[n].get('eventList', []):
                k = EVTYPE.get(e['eventType'], str(e['eventType']))
                ev[k] = ev.get(k, 0) + 1
        print(f'{len(names)} objects, {len(rooms)} rooms; events: ' + ', '.join(f'{k} {v}' for k, v in sorted(ev.items())))


if __name__ == '__main__':
    main()
