#!/usr/bin/env python3
"""HD 1.2.2's sounds (refs/hd/src/sounds: 8 music tracks, 59 effects, 440 s) as signed 8-bit PCM for the CPS3 sound
chip (PLAN.md P6; method from ../maldita.castilla-cps3/tools/snd3.py).

    tools/hdsound.py <hd src dir> <out dir> [rate]        -> <out dir>/snd.bin, snd.h, snd.txt

All sounds at one rate (default 32,000 Hz: 14.1 MB, inside the 16 MB the hardware and jtcps3 address). Each sound is
decoded by ffmpeg to mono at the rate, scaled by its .yy volume x MASTER, rounded and clipped to -128..127
(the OGG music decodes with peaks up to 1.49: at most 46 samples, 0.004%, clip; snd.txt counts them). Music
(the m* sounds, played looped by the game) loops back to its first sample, as GameMaker restarts a looped file;
effects play once. snd.bin's byte k is the sample flash's byte k (cps3asset.Flash.sample puts it at offset SND_AT).
snd.h: per sound (enum SND_<name>, the project's sound order by name) the flash offset of start / end / loop, the
step (4096 = one sample per chip output sample at 37,286.6 Hz) and the volume.
"""
import json
import os
import re
import subprocess
import sys

import numpy as np

CHIP = 42954545 / 3 / 384          # the chip's output rate (MAME cps3_a.cpp), 37,286.6 Hz
WINDOW = 16 << 20                  # samples past 16 MB are not played by the hardware / jtcps3 (cps3-testgame atest)
MASTER = 0.75                      # Maldita's level: full scale -> 3/8 of the voice range, room for several voices
VOICE = 0x4000                     # the volume register value for a sound at .yy volume 1 (SDK: 0x4000 moderate)


def load_yy(path):
    t = open(path, encoding='utf-8-sig').read()
    return json.loads(re.sub(r',(\s*[}\]])', r'\1', t))


def decode(path, rate):
    raw = subprocess.run(['ffmpeg', '-v', 'error', '-i', path, '-ac', '1', '-ar', str(rate), '-f', 'f32le', '-'],
                         check=True, capture_output=True).stdout
    return np.frombuffer(raw, dtype='<f4').astype(np.float64)


def main():
    src, out = sys.argv[1], sys.argv[2]
    rate = int(sys.argv[3]) if len(sys.argv) > 3 else 32000
    names = sorted(n for n in os.listdir(os.path.join(src, 'sounds'))
                   if os.path.exists(os.path.join(src, 'sounds', n, n + '.yy')))
    img = bytearray()
    rows, report = [], []
    for n in names:
        y = load_yy(os.path.join(src, 'sounds', n, n + '.yy'))
        pcm = decode(os.path.join(src, 'sounds', n, y['soundFile']), rate)
        q = np.clip(np.round(pcm * 127 * MASTER), -128, 127).astype(np.int8)
        music = n.startswith('m')
        start = len(img)
        img += q.tobytes()
        end = len(img)
        if end > WINDOW:
            raise SystemExit(f'{n}: ends at {end}, past the 16 MB the sound chip addresses')
        err = pcm * 127 * MASTER - q
        sig = np.mean((pcm * 127 * MASTER) ** 2) or 1e-12
        snr = 10 * np.log10(sig / max(np.mean(err ** 2), 1e-12))
        rows.append((n, start, end, start if music else end, int(round(4096 * rate / CHIP)),
                     int(round(VOICE * float(y.get('volume', 1.0)))), int(music)))
        clip = int(np.sum(np.abs(pcm * 127 * MASTER) > 127.5))
        report.append(f'{n:20s} {len(q) / rate:7.2f} s  {"music " if music else "effect"}  SNR {snr:5.1f} dB  '
                      f'peak {np.max(np.abs(pcm)):.3f}  clipped {clip}')
    os.makedirs(out, exist_ok=True)
    open(os.path.join(out, 'snd.bin'), 'wb').write(bytes(img))
    hdr = '/* generated by tools/hdsound.py from refs/hd/src (Spelunky Classic HD 1.2.2): do not edit */'
    h = [hdr, '#ifndef SND_H', '#define SND_H', '#include <stdint.h>', '', 'enum snd {']
    h += [f'    SND_{r[0]},' for r in rows] + ['    SND_COUNT', '};', '',
          f'#define SND_RATE {rate}u', f'#define SND_BYTES {len(img)}u', '',
          '/* flash offsets from SND_AT (the build places snd.bin), chip step, volume register, looped */',
          'struct snddef { uint32_t start, end, loop; uint16_t step; int16_t vol; uint8_t looped; };',
          'static const struct snddef snddefs[SND_COUNT] = {']
    h += [f'    {{ {r[1]}u, {r[2]}u, {r[3]}u, {r[4]}, {r[5]}, {r[6]} }},  /* {r[0]} */' for r in rows]
    h += ['};', '', '#endif', '']
    open(os.path.join(out, 'snd.h'), 'w').write('\n'.join(h))
    open(os.path.join(out, 'snd.txt'), 'w').write('\n'.join(report) + '\n')
    print(f'{len(rows)} sounds, {len(img) / 2**20:.2f} MB at {rate} Hz (window {WINDOW >> 20} MB)')


if __name__ == '__main__':
    main()
