#!/usr/bin/env python3
"""The HUD's art that tools/hdsprites.py does not convert (it reads refs/hd/src/sprites only): HD's English sprite
fonts and the money sign, loaded at run time by HD from datafiles (scripts/scrInit: global.fontLargeDefault /
fontSmallDefault from locale/locales/en/charset/charset.png / charset_small.png; scripts/setLocale: global.fontLarge
/ fontSmall from the same files for "en"; scripts/loadLocalizedSprites: global.sMoneySignNew from images/money_sign.png,
global.sSmallCollectNew from images/small_collect.png: sprite_add(.., 20 frames, .., origin 4, 4), the price tag oItem /
oDamsel draw at y - 12).

    tools/hudart.py <hd src dir> <gen dir>      (after tools/hdsprites.py: reads <gen dir>/gfx.json)

Writes <gen dir>/hudart.h, hud.bin (tiles), hud.json (flash offsets, palettes). Layout:
  tiles from HUD_FIRST_TILE = gfx first_tile + ntiles, at flash HUD_TILES_AT (after gfx.bin, 64 KB aligned):
    large font glyph k (16 x 16)          HUD_FIRST_TILE + k                 k = character - 32 (charset ' '..'Z')
    small font glyph k (8 x 8, top-left)  HUD_FIRST_TILE + HUD_NGLYPHS + k
    money sign (16 x 16)                  HUD_FIRST_TILE + 2 * HUD_NGLYPHS
    price tag frame k (8 x 10, top-left)  HUD_FIRST_TILE + 2 * HUD_NGLYPHS + 1 + k      k = 0 .. 19
  palettes (colour 0 transparent): colour code HUD_PAL (the art's colours) at flash HUD_PAL_AT; colour code
  HUD_PAL + 1 at HUD_PAL_AT + 512: the same colours multiplied by c_yellow (255, 255, 0), as draw_text with
  draw_set_color(c_yellow) blends them.
Colours: each source colour to the nearest 5-bit value under jtcps3's expansion (tools/hdsprites.py bgr555).
"""
import json
import os
import sys

from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import hdsprites  # noqa: E402

CHARSET = ''.join(chr(c) for c in range(32, 91))
LOC = 'datafiles/locale/locales/en'
HUD_PAL = 2


def sources(src):
    cs = open(os.path.join(src, LOC, 'charset', 'charset')).read().strip('\n')
    if cs != CHARSET:
        raise SystemExit(f'charset is {cs!r}, expected {CHARSET!r}')
    return (Image.open(os.path.join(src, LOC, 'charset', 'charset.png')).convert('RGBA'),
            Image.open(os.path.join(src, LOC, 'charset', 'charset_small.png')).convert('RGBA'),
            Image.open(os.path.join(src, LOC, 'images', 'money_sign.png')).convert('RGBA'),
            Image.open(os.path.join(src, LOC, 'images', 'small_collect.png')).convert('RGBA'))


def tint(rgb, blend):
    """GameMaker's draw colour: each channel multiplied by the blend colour's"""
    return tuple(c * b // 255 for c, b in zip(rgb, blend))


def main():
    src, gen = sys.argv[1], sys.argv[2]
    meta = json.load(open(os.path.join(gen, 'gfx.json')))
    large, small, money, collect = sources(src)
    rgbs = []                        # palette index - 1 -> source (r, g, b)
    index = {}

    def cell(im, x0, y0, w, h):
        t = bytearray(256)
        px = im.load()
        for y in range(h):
            for x in range(w):
                r, g, b, a = px[x0 + x, y0 + y]
                if a >= 128:
                    k = hdsprites.bgr555(r, g, b)
                    if k not in index:
                        index[k] = len(rgbs) + 1
                        rgbs.append((r, g, b))
                    t[16 * y + x] = index[k]
        return bytes(t)

    n = len(CHARSET)
    tiles = [cell(large, 16 * k, 0, 16, 16) for k in range(n)]
    tiles += [cell(small, 8 * k, 0, 8, 8) for k in range(n)]
    tiles.append(cell(money, 0, 0, 16, 16))
    tw = collect.width // 20                     # sprite_add's 20 frames side by side
    tiles += [cell(collect, tw * k, 0, tw, collect.height) for k in range(20)]
    if len(rgbs) > 255:
        raise SystemExit('more than 255 HUD colours')
    pal = [0] + [hdsprites.bgr555(*c) for c in rgbs]
    yel = [0] + [hdsprites.bgr555(*tint(c, (255, 255, 0))) for c in rgbs]
    pal += [0] * (256 - len(pal))
    yel += [0] * (256 - len(yel))
    first = meta['first_tile'] + meta['ntiles']
    end = meta['tiles_at'] + 256 * meta['ntiles']
    tiles_at = (end + 0xffff) & ~0xffff
    pal_at = meta['pal_at'] + 512 * (HUD_PAL - 1)      # after the game palette (colour code 1, 256 words)
    open(os.path.join(gen, 'hud.bin'), 'wb').write(b''.join(tiles))
    json.dump({'tiles_at': tiles_at, 'pal_at': pal_at, 'first_tile': first, 'ntiles': len(tiles), 'pal': HUD_PAL,
               'palette': pal, 'palette_yellow': yel, 'rgb': rgbs}, open(os.path.join(gen, 'hud.json'), 'w'))
    h = ['/* generated by tools/hudart.py from refs/hd/src datafiles (HD 1.2.2 English fonts, money sign): do not edit */',
         '#ifndef HUDART_H', '#define HUDART_H',
         f'#define HUD_TILES_AT 0x{tiles_at:x}u', f'#define HUD_PAL_AT 0x{pal_at:x}u      /* two palettes of 256 */',
         f'#define HUD_FIRST_TILE 0x{first:x}u', f'#define HUD_NTILES {len(tiles)}u',
         f'#define HUD_PAL {HUD_PAL}u                 /* colour code: white text, the art as it is */',
         f'#define HUD_PAL_YELLOW {HUD_PAL + 1}u          /* colour code: c_yellow text */',
         f'#define HUD_NGLYPHS {n}u                /* characters 32 .. {31 + n} */',
         '#define HUD_GLYPH_LARGE(c) (HUD_FIRST_TILE + (unsigned)(c) - 32u)',
         '#define HUD_GLYPH_SMALL(c) (HUD_FIRST_TILE + HUD_NGLYPHS + (unsigned)(c) - 32u)',
         '#define HUD_TILE_MONEYSIGN (HUD_FIRST_TILE + 2u * HUD_NGLYPHS)',
         '#define HUD_TILE_COLLECT(k) (HUD_FIRST_TILE + 2u * HUD_NGLYPHS + 1u + (unsigned)(k))  /* price tag, 20 */',
         f'#define HUD_COLLECT_XORIG 4\n#define HUD_COLLECT_YORIG 4\n#define HUD_COLLECT_FRAMES 20',
         '#endif', '']
    open(os.path.join(gen, 'hudart.h'), 'w').write('\n'.join(h))
    print(f'{len(tiles)} HUD tiles from {first:#x} at flash {tiles_at:#x}, {len(rgbs)} colours, palettes at {pal_at:#x}')


if __name__ == '__main__':
    main()
