#!/usr/bin/env python3
"""HUD host model and checks (src/hud, tests/hud). The model draws HD's scrDrawHUD and showMessages from HD's own
PNGs (refs/hd/src/sprites/*, the datafiles fonts and money sign), independently of the C code and of the converters.

    tools/hudcheck.py cases <cases.json> <out.h>               the cases as C (tests/hud/main.c)
    tools/hudcheck.py expect <cases.json> <hd src> <out dir>   expect_<k>.png: MAME's 384 x 224 screen for case k
                                                               (view lines 8.., X zoom 0x35), view_<k>.png 320 x 240
    tools/hudcheck.py hd <cases.json> <hd src> <k> <shot.png> <gui.png> <display_w> [mask.png]
        compare against the HD runner: the model's HUD for case k drawn over the runner's frame without the GUI
        (application_surface, shot.png) must equal the runner's screen with its GUI (gui.png), in 5-bit colour, over
        the first 320 columns; display_w is the runner's GUI width (message centring)

Case fields (tests/hud/cases.json): hud_state's (src/hud/hud.h); held as a HUD_HELD_* name, items as HUD_* names,
messages as a string or a list of parts with the yellow part indices (drawHighlightedMessage).
"""
import json
import os
import re
import sys

from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import hdsprites  # noqa: E402

ZOOM = 0x35
CROP = 8
HELD = ['NONE', 'ROCK', 'JAR', 'SKULL', 'FISHBONE', 'ARROW', 'MACHETE', 'MATTOCK', 'MATTOCKHEAD', 'PISTOL',
        'WEBCANNON', 'TELEPORTER', 'SHOTGUN', 'BOW', 'SCEPTRE', 'FLARE', 'KEY', 'OTHER']
# scrDrawHUD :76-94, pickupItemType -> sprite
HELD_SPR = {'ROCK': 'sRock', 'JAR': 'sJar', 'SKULL': 'sSkull', 'FISHBONE': 'sFishBone', 'ARROW': 'sArrowRight',
            'MACHETE': 'sMacheteRight', 'MATTOCK': 'sMattockRight', 'MATTOCKHEAD': 'sMattockHead',
            'PISTOL': 'sPistolRight', 'WEBCANNON': 'sWebCannonR', 'TELEPORTER': 'sTeleporter',
            'SHOTGUN': 'sShotgunRight', 'BOW': 'sBowDisp', 'SCEPTRE': 'sSceptreRight', 'FLARE': 'sFlare',
            'KEY': 'sKeyRight'}
ITEMS = ['UDJAT', 'ANKH', 'CROWN', 'KAPALA', 'SPECTACLES', 'GLOVES', 'MITT', 'SPRINGSHOES', 'SPIKESHOES', 'CAPE',
         'JETPACK', 'COMPASS', 'PARACHUTE']
LOC = 'datafiles/locale/locales/en'


def msg_parts(c, k):
    m = c.get(f'message{k}', '')
    if isinstance(m, str):
        return [m], set()
    return m, set(c.get(f'message{k}_yellow', []))


def msg_text_mask(c, k):
    parts, yel = msg_parts(c, k)
    text, mask = '', 0
    for i, p in enumerate(parts):
        if i in yel:
            for j in range(len(p)):
                mask |= 1 << (len(text) + j)
        text += p
    return text, mask


# ---------------------------------------------------------------- C cases

def write_c(cases, out):
    L = ['/* generated by tools/hudcheck.py from tests/hud/cases.json: do not edit */', '#include "hud.h"',
         'static const struct hud_state hud_cases[] = {']
    for c in cases:
        items = ' | '.join(f'HUD_{i}' for i in c.get('items', [])) or '0'
        m1, y1 = msg_text_mask(c, 1)
        m2, y2 = msg_text_mask(c, 2)
        L.append(f'    {{ /* {c["name"]} */ .visible = {c.get("visible", 1)}, .life = {c.get("life", 0)}, '
                 f'.bombs = {c.get("bombs", 0)}, .ropes = {c.get("ropes", 0)}, .money = {c.get("money", 0)}, '
                 f'.collect = {c.get("collect", 0)}, .sticky_bombs = {c.get("sticky_bombs", 0)}, '
                 f'.held = HUD_HELD_{c.get("held", "NONE")}, .items = {items}, .udjat_blink = {c.get("udjat_blink", 0)}, '
                 f'.blood_level = {c.get("blood_level", 0)}, .arrows = {c.get("arrows", 0)}, .anim = {c.get("anim", 0)}, '
                 f'.exit_x = {c.get("exit_x", 0)}, .exit_y = {c.get("exit_y", 0)}, .view_x = {c.get("view_x", 0)}, '
                 f'.view_y = {c.get("view_y", 0)}, .message_timer = {c.get("message_timer", 0)}, '
                 f'.message1 = {{ "{m1}", {{ 0x{y1 & 0xffffffff:x}u, 0x{y1 >> 32:x}u }} }}, '
                 f'.message2 = {{ "{m2}", {{ 0x{y2 & 0xffffffff:x}u, 0x{y2 >> 32:x}u }} }} }},')
    L += ['};', '#define NCASES (sizeof hud_cases / sizeof hud_cases[0])', '']
    open(out, 'w').write('\n'.join(L))


# ---------------------------------------------------------------- the model

class Art:
    def __init__(self, src):
        self.src = src
        self.cache = {}
        self.large = Image.open(os.path.join(src, LOC, 'charset', 'charset.png')).convert('RGBA')
        self.small = Image.open(os.path.join(src, LOC, 'charset', 'charset_small.png')).convert('RGBA')
        self.money = Image.open(os.path.join(src, LOC, 'images', 'money_sign.png')).convert('RGBA')

    def sprite(self, name):
        if name not in self.cache:
            y = hdsprites.load_yy(os.path.join(self.src, 'sprites', name, name + '.yy'))
            sq = y.get('sequence', {})
            frames = [Image.open(os.path.join(self.src, 'sprites', name, f['name'] + '.png')).convert('RGBA')
                      for f in y['frames']]
            self.cache[name] = (int(sq.get('xorigin', 0)), int(sq.get('yorigin', 0)), frames)
        return self.cache[name]


class View:
    """GUI / view pixels as bgr555 words (None: nothing drawn)"""
    def __init__(self, w=320, h=240):
        self.w, self.h = w, h
        self.px = [[None] * w for _ in range(h)]

    def blit(self, im, x, y, blend=(255, 255, 255), cx=0, cy=0, cw=None, ch=None):
        p = im.load()
        cw = im.width if cw is None else cw
        ch = im.height if ch is None else ch
        for j in range(ch):
            Y = y + j
            if not 0 <= Y < self.h:
                continue
            for i in range(cw):
                X = x + i
                if not 0 <= X < self.w:
                    continue
                r, g, b, a = p[cx + i, cy + j]
                if a >= 128:
                    r, g, b = (r * blend[0] // 255, g * blend[1] // 255, b * blend[2] // 255)
                    self.px[Y][X] = hdsprites.bgr555(r, g, b)


def draw_sprite(v, art, name, img, x, y):
    xo, yo, frames = art.sprite(name)
    v.blit(frames[int(img) % len(frames)], x - xo, y - yo)


WHITE, YELLOW = (255, 255, 255), (255, 255, 0)


def draw_text(v, art, text, size, x, y, colour=WHITE, colours=None):
    """draw_text with a non-proportional sprite font (font_add_sprite_ext(spr, charset, false, 0)): glyph k of the
    charset at x + k * width, top at y; colours: per character blend (drawHighlightedMessage)"""
    im, w = (art.large, 16) if size == 'large' else (art.small, 8)
    for k, ch in enumerate(str(text)):
        i = ord(ch) - 32
        if 0 <= i < 59:
            v.blit(im, x + k * w, y, colours[k] if colours else colour, cx=i * w, cy=0, cw=w, ch=w)


def model(c, art, display_w=320, v=None, port=False):
    """HD's HUD for case c; port: the port's own placement (the MAME screen): the compass's bottom row 8 lines
    higher (src/hud hud.c COMPASS_BOTTOM_Y, not in HD: the screen ends at view line 231)"""
    v = v or View()
    if c.get('visible', 1):
        lifeX, bombX, ropeX, moneyX = 8, 64, 120, 176
        a = c.get('anim', 0)
        draw_sprite(v, art, 'sHeart', a, lifeX, 8)
        life = max(c.get('life', 0), 0)
        draw_text(v, art, life, 'large', lifeX + 16, 8)
        draw_sprite(v, art, 'sStickyBombIcon' if c.get('sticky_bombs') else 'sBombIcon', a, bombX, 8)
        draw_text(v, art, c.get('bombs', 0), 'large', bombX + 16, 8)
        draw_sprite(v, art, 'sRopeIcon', a, ropeX, 8)
        draw_text(v, art, c.get('ropes', 0), 'large', ropeX + 16, 8)
        v.blit(art.money, moneyX, 6)
        draw_text(v, art, c.get('money', 0), 'large', moneyX + 16, 8)
        items = set(c.get('items', []))
        small = c.get('message_timer', 0) > 0
        if 'COMPASS' in items:
            ex, ey, vx, vy = c.get('exit_x', 0), c.get('exit_y', 0), c.get('view_x', 0), c.get('view_y', 0)
            S = 'Small' if small else ''
            by = 224 - CROP if port else 224
            if ey > vy + 240:
                if ex < vx:
                    draw_sprite(v, art, f'sCompass{S}LL', a, 0, by)
                elif ex > vx + 320 - 16:
                    draw_sprite(v, art, f'sCompass{S}LR', a, 304, by)
                else:
                    draw_sprite(v, art, f'sCompass{S}Down', a, ex - vx, by)
            elif ex < vx:
                draw_sprite(v, art, f'sCompass{S}Left', a, 0, ey - vy)
            elif ex > vx + 320 - 16:
                draw_sprite(v, art, f'sCompass{S}Right', a, 304, ey - vy)
        draw_sprite(v, art, 'sHoldItemIcon', a, 8, 24)
        held = c.get('held', 'NONE')
        if held in HELD_SPR:
            draw_sprite(v, art, HELD_SPR[held], a, 16, 32)
        n = 28
        for it, spr in [('UDJAT', None), ('ANKH', 'sAnkhIcon'), ('CROWN', 'sCrownIcon'), ('KAPALA', None),
                        ('SPECTACLES', 'sSpectaclesIcon'), ('GLOVES', 'sGlovesIcon'), ('MITT', 'sMittIcon'),
                        ('SPRINGSHOES', 'sSpringShoesIcon'), ('SPIKESHOES', 'sSpikeShoesIcon'), ('CAPE', 'sCapeIcon'),
                        ('JETPACK', 'sJetpackIcon'), ('COMPASS', 'sCompassIcon'), ('PARACHUTE', 'sParachuteIcon')]:
            if it not in items:
                continue
            if it == 'UDJAT':
                draw_sprite(v, art, 'sUdjatEyeIcon2' if c.get('udjat_blink') else 'sUdjatEyeIcon', a, n, 24)
            elif it == 'KAPALA':
                bl = c.get('blood_level', 0)
                f = 0 if bl == 0 else 1 if bl <= 2 else 2 if bl <= 4 else 3 if bl <= 6 else 4 if bl <= 8 else None
                if f is not None:
                    draw_sprite(v, art, 'sKapalaIcon', f, n, 24)
            else:
                draw_sprite(v, art, spr, a, n, 24)
            n += 20
        if held == 'BOW':
            for _ in range(c.get('arrows', 0)):
                draw_sprite(v, art, 'sArrowIcon', a, n, 24)
                n += 4
        if c.get('collect', 0) > 0:
            draw_text(v, art, '+' + str(c['collect']), 'small', moneyX, 24, YELLOW)
    if c.get('message_timer', 0) > 0:
        for k, y in ((1, 216), (2, 224)):
            parts, yel = msg_parts(c, k)
            text = ''.join(parts)
            cols = []
            for i, p in enumerate(parts):
                cols += [YELLOW if i in yel else WHITE] * len(p)
            x = -((len(text) * 8 - display_w) // 2)          # ceil((display_w - strLen) / 2)
            draw_text(v, art, text, 'small', x, y, colours=cols)
    return v


def screen(v):
    """MAME's 384 x 224 screen of a 320 x 240 view: lines CROP.., X zoom ZOOM (tools/viewlevel.py screen), backdrop 0"""
    fsz = (ZOOM << 16) // 0x40
    clip_r = ((384 * fsz + 0x8000) >> 16) - 1
    im = Image.new('RGB', (384, 224))
    px = im.load()
    for y in range(224):
        row = v.px[y + CROP]
        for x in range(384):
            sx = (x * fsz) >> 16
            w = row[sx] if sx <= clip_r and sx < 320 else None
            w = w or 0
            px[x, y] = ((w & 31) << 3, (w >> 5 & 31) << 3, (w >> 10 & 31) << 3)
    return im


def view_png(v):
    im = Image.new('RGB', (v.w, v.h))
    p = im.load()
    for y in range(v.h):
        for x in range(v.w):
            w = v.px[y][x] or 0
            p[x, y] = ((w & 31) << 3, (w >> 5 & 31) << 3, (w >> 10 & 31) << 3)
    return im


def hd_compare(c, art, shot, gui, display_w, mask=None):
    s = Image.open(shot).convert('RGB')
    g = Image.open(gui).convert('RGB')
    W, H = 320, 240
    v = View(W, H)
    sp = s.load()
    for y in range(H):
        for x in range(W):
            v.px[y][x] = hdsprites.bgr555(*sp[x, y])
    model(c, art, display_w, v)
    gp = g.load()
    n = 0
    m = Image.new('L', (W, H)) if mask else None
    for y in range(H):
        for x in range(W):
            if v.px[y][x] != hdsprites.bgr555(*gp[x, y]):
                n += 1
                if m:
                    m.putpixel((x, y), 255)
    if m:
        m.save(mask)
    return n


def main():
    a = sys.argv[1:]
    if not a:
        sys.exit(__doc__)
    cases = json.load(open(a[1]))
    if a[0] == 'cases':
        write_c(cases, a[2])
    elif a[0] == 'expect':
        art = Art(a[2])
        os.makedirs(a[3], exist_ok=True)
        for k, c in enumerate(cases):
            v = model(c, art, port=True)
            screen(v).save(os.path.join(a[3], f'expect_{k}.png'))
            view_png(v).save(os.path.join(a[3], f'view_{k}.png'))
        print(f'{len(cases)} expected screens in {a[3]}')
    elif a[0] == 'hd':
        art = Art(a[2])
        k = int(a[3])
        n = hd_compare(cases[k], art, a[4], a[5], int(a[6]), a[7] if len(a) > 7 else None)
        print(f'case {k} ({cases[k]["name"]}): {n} of {320 * 240} pixels differ from the runner')
        sys.exit(1 if n else 0)
    else:
        sys.exit(__doc__)


if __name__ == '__main__':
    main()
