/* tools/mkrecip.c: the thresholds of src/game/precip.h (moveTo's round(1 / frac(|v|)) without soft-float).
 *   cc -std=c99 -O2 -ffp-contract=off -DMKRECIP_GEN -Isrc/game -o build/mkrecip_gen tools/mkrecip.c
 *   build/mkrecip_gen gen > src/game/preciptab.h  the table: T[k], the smallest double f in (0, 1) with N(f) <= k
 *   cc -std=c99 -O2 -ffp-contract=off -Isrc/game -o build/mkrecip tools/mkrecip.c
 *   build/mkrecip check [millions]                 precip_parts against the binary64 formula (random v, and v around
 *                                                  every threshold +-2 ulp with integer parts 0 .. 9); 0 differ */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "pnum.h"
#define K 128
#ifndef MKRECIP_GEN
#include "precip.h"
#endif

static double bd(uint64_t u) { double d; memcpy(&d, &u, 8); return d; }
static uint64_t db(double d) { uint64_t u; memcpy(&u, &d, 8); return u; }
static int32_t nof(double f) { return dround((double)((double)1.0 / f)); }   /* NRECIP_ROUND */

/* the formula as moveTo computes it */
static void ref(double a, int32_t *n, int32_t *fl, int *neg)
{
    double x = a < 0 ? -a : a, f = dfrac(x);
    *n = gcmp_d(f, 0) != 0 ? nof(f) : 0;
    *fl = dfloor(x);
    *neg = a < 0;
}

static uint64_t T[K + 1];

static void gen_table(void)
{
    int k;
    for (k = 1; k <= K; k++) {
        uint64_t lo = db(1.0 / 8192), hi = db(1.0) - 1;    /* N(lo) > k, N(hi) = 1 <= k */
        if (!(nof(bd(lo)) > k && nof(bd(hi)) <= k)) { fprintf(stderr, "bracket k=%d\n", k); exit(1); }
        while (hi - lo > 1) {
            uint64_t mid = lo + (hi - lo) / 2;
            if (nof(bd(mid)) <= k) hi = mid; else lo = mid;
        }
        T[k] = hi;
    }
}

/* Q0.64 of a double in [2^-8, 1) */
static uint64_t q64(double f)
{
    uint64_t u = db(f), m = (u & ((1ull << 52) - 1)) | (1ull << 52);
    int e = (int)((u >> 52) & 0x7ff);
    return m << (e - 1011);
}

int main(int argc, char **argv)
{
    int k;
    if (argc > 1 && !strcmp(argv[1], "gen")) {
        gen_table();
        if (bd(T[K]) < 1.0 / 256) { fprintf(stderr, "T[K] below 2^-8\n"); return 1; }
        printf("/* generated by tools/mkrecip.c gen: T[k] (k = 1 .. %d), the smallest binary64 f in (0, 1) with\n"
               "   round(1.0 / f) <= k (GML round, half to even), as frac * 2^64 in high / low words */\n", K);
        printf("#define PRECIP_K %d\n", K);
        printf("static const uint32_t precip_th[%d] = {", K);
        for (k = 1; k <= K; k++) printf("%s%s0x%08xu", k > 1 ? "," : "", (k - 1) % 6 ? " " : "\n    ", (unsigned)(q64(bd(T[k])) >> 32));
        printf(" };\nstatic const uint32_t precip_tl[%d] = {", K);
        for (k = 1; k <= K; k++) printf("%s%s0x%08xu", k > 1 ? "," : "", (k - 1) % 6 ? " " : "\n    ", (unsigned)q64(bd(T[k])));
        printf(" };\n");
        return 0;
    }
#ifndef MKRECIP_GEN
    if (argc > 1 && !strcmp(argv[1], "check")) {
        long n = argc > 2 ? atol(argv[2]) * 1000000L : 20000000L, i, bad = 0, done = 0, fb = 0;
        uint64_t s = 88172645463325252ull;
        gen_table();
        for (i = 0; i < n; i++) {
            double a;
            int32_t r1, f1, r2, f2;
            int n1, n2, mode;
            s ^= s << 13; s ^= s >> 7; s ^= s << 17;
            mode = (int)(s % 4);
            if (mode == 0) {                               /* a threshold +-2 ulp, integer part 0 .. 9, either sign */
                int kk = 1 + (int)((s >> 8) % K), d = (int)((s >> 20) % 5) - 2, ip = (int)((s >> 30) % 10);
                double f = bd(T[kk] + (uint64_t)(int64_t)d);
                a = ip + f;                                /* (rounded when ip > 0: still near the threshold) */
                if ((s >> 40) & 1) a = -a;
            } else if (mode == 1) {                        /* any f in (0, 1) */
                a = bd(db(1.0 / 8192) + (s >> 11) % (db(1.0) - db(1.0 / 8192)));
            } else if (mode == 2) {                        /* velocity-like: k / 2^j and decimal steps */
                a = (double)((int64_t)(s >> 12) % 2000) / (double)(1 + (s >> 40) % 1000);
            } else                                         /* random bits, a range of exponents */
                a = bd(((s >> 11) & ((1ull << 52) - 1)) | ((uint64_t)(1000 + (s >> 3) % 50) << 52) | (s & (1ull << 63)));
            if (!precip_parts(a, &r1, &f1, &n1)) { fb++; continue; }
            ref(a, &r2, &f2, &n2);
            done++;
            if (r1 != r2 || f1 != f2 || n1 != n2) {
                if (bad++ < 10) printf("BAD a=%.17g table %d %d %d formula %d %d %d\n", a, r1, f1, n1, r2, f2, n2);
            }
        }
        for (k = 1; k <= K; k++) {                         /* every threshold exactly, and its neighbours */
            int d;
            for (d = -2; d <= 2; d++) {
                double a = bd(T[k] + (uint64_t)(int64_t)d);
                int32_t r1, f1, r2, f2;
                int n1, n2;
                if (!precip_parts(a, &r1, &f1, &n1)) { fb++; continue; }
                ref(a, &r2, &f2, &n2);
                done++;
                if (r1 != r2 || f1 != f2 || n1 != n2) bad++;
            }
        }
        printf("mkrecip check: %ld compared, %ld fell back, %ld differ\n", done, fb, bad);
        return bad != 0;
    }
#endif
    fprintf(stderr, "usage: mkrecip gen | check [millions]\n");
    return 2;
}
