#!/usr/bin/env python3
"""P3 level viewer data and expected frames (PLAN.md P3): one record of an HD reference trace (tools/tracer.py) as
a C table for tests/view, and the screens the CPS3 must show for a list of cameras.

    tools/viewlevel.py c <trace.bin> <names> <rec> <gen dir> <out.h>
    tools/viewlevel.py expect <trace.bin> <names> <rec> <gen dir> <out dir> <vx,vy> ...   (zoom 0x35, MAME's formula)

Drawing model (interim, until the runner's drawing is traced: depth is the object's GM8 depth, equal depths in
creation order, image_xscale not in the trace yet):
  - the room background (bgCave, tiled; 2147483500 deep) on tilemap 0;
  - instances deeper than the terrain (depth > 100), as sprites;
  - terrain on tilemap 1: instances of oSolid's family at 16-px cell positions whose frame is one 16x16 piece;
  - every other visible instance with a sprite, as sprites, deepest first.
The view is 320x240 at (vx, vy); the screen shows its lines 8-231 (PLAN §1), stretched by X zoom 0x35.
"""
import json
import os
import re
import sys

from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import tracer  # noqa: E402

ZOOM = 0x35
CROP = 8
TERRAIN_DEPTH = 100


def table(path, name):
    t = open(path).read()
    body = t[t.index(name):]
    body = body[body.index('{') + 1:body.index('\n};')]
    return [list(map(lambda v: int(v, 0), re.findall(r'-?0x[0-9a-f]+|-?\d+', ln.split('/*')[0])))
            for ln in body.splitlines() if '{' in ln]


class Gen:
    def __init__(self, gen):
        c = os.path.join(gen, 'sprites.c')
        self.spr = table(c, 'sprdefs[')
        self.frm = table(c, 'framedefs[')
        self.pcs = table(c, 'piecedefs[')
        self.sprname = [ln.strip().strip('",') for ln in
                        open(c).read().split('sprnames[SPR_COUNT] = {')[1].split('};')[0].splitlines() if ln.strip()]
        self.sprid = {n: i for i, n in enumerate(self.sprname)}
        oc = open(os.path.join(gen, 'objects.c')).read()
        body = oc[oc.index('objdefs[OBJ_COUNT] = {'):]
        body = body[:body.index('\n};')]
        self.obj = {}
        names = []
        for m in re.finditer(r'\{ "(\w+)", (OBJ_\w+), [^,]+, [^,]+, (\d), (\d), (\d), (-?\d+) \}', body):
            names.append(m.group(1))
            self.obj[m.group(1)] = dict(parent=m.group(2)[4:], visible=int(m.group(4)), depth=int(m.group(6)))
        self.meta = json.load(open(os.path.join(gen, 'gfx.json')))
        self.gfx = open(os.path.join(gen, 'gfx.bin'), 'rb').read()

    def is_a(self, o, anc):
        while o and o != 'NONE':
            if o == anc:
                return True
            o = self.obj.get(o, {}).get('parent')
        return False

    def frame(self, spr, img):
        s = self.spr[spr]
        return s[9] + int(img) % s[10]


def level(trace, names_path, rec, g):
    names = tracer.load_names(names_path)
    for hd, insts in tracer.records(open(trace, 'rb').read()):
        if hd['rec'] == rec:
            break
    else:
        raise SystemExit(f'record {rec} not in {trace}')
    terrain, sprites = [], []
    order = list(reversed(insts))                   # the trace lists instances newest first
    for k, i in enumerate(order):
        if i['spr'] < 0:
            continue
        on, sn = names['O'][i['obj']], names['S'][i['spr']]
        o = g.obj[on]
        if not o['visible'] or sn not in g.sprid:
            continue
        sid = g.sprid[sn]
        f = g.frame(sid, i['img'])
        p0, npc = g.frm[f]
        x, y = int(i['x']), int(i['y'])
        s = g.spr[sid]
        one = npc == 1 and g.pcs[p0][2:4] == [1, 1] and g.pcs[p0][0] == -s[2] and g.pcs[p0][1] == -s[3]
        if g.is_a(on, 'oSolid') and one and x % 16 == 0 and y % 16 == 0 and o['depth'] == TERRAIN_DEPTH:
            terrain.append((x // 16, y // 16, g.pcs[p0][4]))
        else:
            sprites.append((o['depth'], k, sid, f, x, y))
    sprites.sort(key=lambda s: (-s[0], s[1]))
    return terrain, sprites


def write_c(out, terrain, sprites, g):
    bg = g.sprid['bgCave']
    bgf = g.spr[bg][9]
    bp0, bn = g.frm[bgf]
    L = ['/* generated by tools/viewlevel.py: do not edit */', '#include <stdint.h>',
         f'#define VIEW_NTERRAIN {len(terrain)}', f'#define VIEW_NSPRITES {len(sprites)}',
         f'#define VIEW_BG_PIECE {bp0}', f'#define VIEW_BG_NPIECES {bn}',
         'static const uint16_t view_terrain[][3] = {']
    L += [f'    {{ {cx}, {cy}, 0x{t:x} }},' for cx, cy, t in terrain]
    L += ['};', '/* depth, frame, x, y (deepest first) */', 'static const int32_t view_sprites[][4] = {']
    L += [f'    {{ {d}, {f}, {x}, {y} }},' for d, _, _, f, x, y in sprites]
    L += ['};', '']
    open(out, 'w').write('\n'.join(L))


def compose(terrain, sprites, g, vx, vy):
    """the 320x240 view as palette indices (0 = backdrop)"""
    W, H = 320, 240
    img = [[0] * W for _ in range(H)]
    first = g.meta['first_tile']

    def blit_tile(tile, px, py, flip=False):
        t = tile - first
        tb = g.gfx[256 * t:256 * t + 256]
        for yy in range(16):
            Y = py + yy
            if 0 <= Y < H:
                row = img[Y]
                for xx in range(16):
                    X = px + xx
                    v = tb[16 * yy + (15 - xx if flip else xx)]
                    if v and 0 <= X < W:
                        row[X] = v

    def blit_frame(f, x, y):
        p0, n = g.frm[f]
        for dx, dy, pw, ph, tile in g.pcs[p0:p0 + n]:
            for i in range(pw):
                for j in range(ph):
                    blit_tile(tile + i * ph + j, x + dx + 16 * i, y + dy + 16 * j)

    # background: bgCave's 64x64 frame repeated from room (0, 0)
    bg = g.sprid['bgCave']
    for ry in range((vy // 64) * 64, vy + H, 64):
        for rx in range((vx // 64) * 64, vx + W, 64):
            blit_frame(g.spr[bg][9], rx - vx, ry - vy)
    for s in sprites:
        if s[0] > TERRAIN_DEPTH:
            blit_frame(s[3], s[4] - vx, s[5] - vy)
    for cx, cy, t in terrain:
        blit_tile(t, 16 * cx - vx, 16 * cy - vy)
    for s in sprites:
        if s[0] <= TERRAIN_DEPTH:
            blit_frame(s[3], s[4] - vx, s[5] - vy)
    return img


def screen(view, g):
    """MAME's 384x224 screen: view lines CROP.., X zoom ZOOM (cps3.cpp's copy with zoom; see tests/zoom)"""
    pal = g.meta['palette']
    fsz = (ZOOM << 16) // 0x40
    clip_r = ((384 * fsz + 0x8000) >> 16) - 1
    im = Image.new('RGB', (384, 224))
    px = im.load()
    for y in range(224):
        row = view[y + CROP]
        for x in range(384):
            sx = (x * fsz) >> 16
            v = row[sx] if sx <= clip_r and sx < 320 else 0
            w = pal[v] if v else 0
            px[x, y] = ((w & 31) << 3, (w >> 5 & 31) << 3, (w >> 10 & 31) << 3)
    return im


def main():
    a = sys.argv[1:]
    g = Gen(a[4])
    terrain, sprites = level(a[1], a[2], int(a[3]), g)
    if a[0] == 'c':
        write_c(a[5], terrain, sprites, g)
        print(f'{len(terrain)} terrain cells, {len(sprites)} sprites')
    elif a[0] == 'expect':
        os.makedirs(a[5], exist_ok=True)
        for k, cam in enumerate(a[6:]):
            vx, vy = map(int, cam.split(','))
            screen(compose(terrain, sprites, g, vx, vy), g).save(os.path.join(a[5], f'expect_{k}.png'))
    else:
        sys.exit(__doc__)


if __name__ == '__main__':
    main()
